Models/EmprestimoModel.cs
namespace EmprestimoDeLivros.Models
{
    public class EmprestimoModel
    {
        public int id { get; set; }
        public string Recebedor { get; set; }
        public string Fornecedor { get; set; }
        public string NomeLivro { get; set; }
        public DateTime DataUltimaAtualizacao { get; set; } = DateTime.Now;

    }
}

Models/ErrorViewModel.cs
namespace EmprestimoDeLivros.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/EmprestimoController.cs
using EmprestimoDeLivros.Data;
using EmprestimoDeLivros.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace EmprestimoDeLivros.Controllers
{    
    public class EmprestimoController : Controller
    {

        readonly private EmprestimoDbContext _db;
        public EmprestimoController(EmprestimoDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<EmprestimoModel> emprestimos = _db.Emprestimos;
            return View(emprestimos);
        }

        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(EmprestimoModel emprestimos)
        {
            if (ModelState.IsValid)
            {
                _db.Emprestimos.Add(emprestimos);
                _db.SaveChanges();
                return RedirectToAction("index");
            }
            return View();
        }

        [HttpDelete]
        public IActionResult Excluir(EmprestimoModel emprestimos)
        {
            _db.Emprestimos.Remove(emprestimos);
            _db.SaveChanges();
            return View();

        }
    }
}

Controllers/HomeController.cs
using EmprestimoDeLivros.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EmprestimoDeLivros.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Emprestimo/Cadastrar.cshtml
@model EmprestimoModel
@{
    ViewData["title"] = "Cadastrar Emprestimo";
}

<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Cadastro De Empréstimos</h1>
    </div>


    <form method="post" asp-controller="Emprestimo" asp-action="Cadastrar">
        <div class="mb-3">
            <label for="Recebedor" class="form-label text-light">Recebedor:</label>
            <input type="text" class="form-control" asp-for="Recebedor" id="Recebedor" placeholder="Quem esta recebendo:">
        </div>

        <div class="mb-3">
            <label for="Fornecedor" class="form-label text-light">Fornecedor:</label>
            <input type="text" class="form-control" asp-for="Fornecedor" id="Fornecedor" placeholder="Quem esta emprestando:">
        </div>

        <div class="mb-3">
            <label for="Livro" class="form-label text-light">Nome Do Livro:</label>
            <input type="text" class="form-control" asp-for="NomeLivro" id="Livro" placeholder="Nome Do Livro">
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Adicionar</button>
            <a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
        </div >
     
    </form>
</div>

Views/Emprestimo/Index.cshtml
@model IEnumerable<EmprestimoModel> 

<div class="container">
    <div class ="d-flex justify-content-between align-itens-center mb-5">
        <h1>Emprestimos</h1>
        <a class="btn btn-success w-40 " asp-controller="Emprestimo" asp-action="Cadastrar">Cadastrar Novo Emprestimo</a>
    </div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Recebedor</th>
                <th scope="col">Fornecedor</th>
                <th scope="col">Livro</th>  
                <th scope="col">Ultima Atualização</th>
            </tr>
        </thead>
        <tbody>
            @if(Model != null)
            {
                foreach(var emprestimo in Model)
                {
                    <tr>
                        <th scope="row">@emprestimo.Recebedor</th>
                        <td>@emprestimo.Fornecedor</td>
                        <td>@emprestimo.NomeLivro</td>
                        <td>@emprestimo.DataUltimaAtualizacao</td>
                            <td> <button class="btn btn-outline-warning w-10" > Atualizar </button> </td>
                            <td><button type="submit" class="btn btn-outline-danger w-10 " method="Delete" asp-controller="Emprestimo" asp-action="Excluir">Excluir</button></td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>


Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmprestimoDeLivros</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmprestimoDeLivros.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EmprestimoDeLivros</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Emprestimo" asp-action="Index">Emprestimos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EmprestimoDeLivros - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>